name: Keep Repository Active

on:
  schedule:
    - cron: '0 0 */30 * *' # Runs every 30 days at midnight UTC
  workflow_dispatch: # For manual testing

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main  # Start with the main branch

      - name: Create or switch to keep-alive branch
        run: |
          # Check if keep-alive branch exists
          if git ls-remote --heads origin keep-alive | grep -q keep-alive; then
            git checkout keep-alive
          else
            git checkout -b keep-alive
          fi

      - name: Create dummy commit
        run: |
          echo "Keep-alive commit at $(date)" >> keep-alive.txt
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add keep-alive.txt
          git commit -m "Keep-alive commit to prevent scheduled workflow disable"
          git push origin keep-alive
